# Generated by Django 4.2 on 2025-04-08 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^\\d{2}/\\d{5}$')]),
        ),
    ]
