# Generated by Django 4.2 on 2025-04-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_alter_medico_crm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='emaiil',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(choices=[('clino geral', 'clinico geral'), ('pediatra', 'pediatra'), ('psiquiatria', 'psiquiatria'), ('car', 'car')], max_length=30),
        ),
    ]
