# Generated by Django 4.2 on 2025-04-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_rename_emaiil_medico_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(choices=[('clino geral', 'clinico geral'), ('pediatra', 'pediatra'), ('psiquiatria', 'psiquiatria'), ('CAR', 'car')], max_length=30),
        ),
    ]
